### PR TITLE
[WIP] Add support for reading from HTTP broadcast streams

### LINKED ISSUE #53: GOTV+ Broadcasting
Hey,

same feature request as the old S1 parser https://github.com/saul/demofile/issues/373

The broadcast URLs for the current major are https://cstv.challengermode.com/major/primary and https://cstv.challengermode.com/major/secondary

I assume its almost identical to the CSGO one, convars are all the same at least

### PR DESCRIPTION
**Pull request by saul**
Closes #53

### CODE REVIEW

**Comment by in0finite** [comment]
It looks good, but have you considered different API design, so that user controls the flow of parsing ? Like with `StartReading()` and `MoveNext()`.

**Comment by saul** [comment]
@in0finite do you need to control the flow tick by tick, or is HTTP fragment by HTTP fragment suffice? A fragment holds a couple of seconds worth of ticks.

**Comment by in0finite** [comment]
Well, I am displaying demo state in real-time, with adjustable speed, with seeking, etc. So yes, I would need to control it tick-by-tick. So probably read current fragment tick-by-tick, when reaching end, request new fragment.

**Comment by saul** [comment]
Recreated this in https://github.com/saul/demofile-net/pull/93 to support driving the parsing with MoveNextAsync

**Pull request closed without merging**
