### PR TITLE
implement non-async API

### PR DESCRIPTION
**Pull request by in0finite**
As I mentioned in #22, I implemented a non-async API.

This would allow us to use library like this:

```cs
void OnButtonClicked()
{
    demo = new DemoParser();
    demo.StartNonAsync(stream);
}

void OnApplicationUpdate()
{
    if (!demo.ReachedEndOfFile)
        demo.ReadNext();
}
```

This means user can have full control of demo parsing, without spawning separate threads in background, can pause demo, seek through demo on demand, and generally use event-driven programming.

Most of the PR is just refactoring, I tried to do it as simple as possible.

### CODE REVIEW

**Comment by in0finite** [comment]
@saul  Could you take a look at this PR ? I need this functionality and am blocked by this.

**Comment by saul** [comment]
Hi @in0finite - many thanks for the contribution and apologies for the delay in getting back to you.

I'm not ready to merge this yet as I need to think a bit more about the best API for stepping through a demo. I have larger changes that would allow you to quickly jump to any point in the demo (rather than at the moment where rewinding requires parsing from the start of the file again).

**Comment by in0finite** [comment]
Hi, it's alright. 

Seeking through file is definitely a nice feature. But I really need a way to step through demo 1 tick at a time (also without async stuff). Could you please integrate any solution for this ? I wouldn't like to constantly get merge conflicts when I try to pull changes.

**Comment by saul** [comment]
Here's a WIP PR - https://github.com/saul/demofile-net/pull/32. Are you still able to use async APIs? I've added `ConfigureAwait(false)` in all of the necessary places in the library, so you should be able to use them from WinForms now.

**Comment by saul** [comment]
Superceded by https://github.com/saul/demofile-net/pull/32 and released as v0.8.1

Many thanks for getting the work started here

**Pull request closed without merging**
